---
# tasks file for gerrit (PostgreSQL specific)

- name: Create Gerrit PostgreSQL database
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db: >
    name={{ gerrit_database_db }}
    encoding='UTF-8'
    state=present

- name: Create Gerrit PostgreSQL database user
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user: >
    name={{ gerrit_database_username }}
    db={{ gerrit_database_db }}
    password={{ gerrit_database_password }}
    priv=ALL
    state=present
